package com.mambocosmo.urzasoracle.services;

import java.sql.Date;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import com.mambocosmo.urzasoracle.DTO.UrzaUserDTO;
import com.mambocosmo.urzasoracle.converters.UrzaUserConverter;
import com.mambocosmo.urzasoracle.entities.UrzaUser;
import com.mambocosmo.urzasoracle.repositories.UrzaUserRepository;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Service
@Data
@EqualsAndHashCode(callSuper = true)

public class UrzaUserService extends GenericService<UrzaUser, UrzaUserDTO, UrzaUserConverter, UrzaUserRepository>
        implements UserDetailsService {

    private final UrzaUserRepository URZAUSEREPOSITORY;

    private final PasswordEncoder passwordEncoder;

    public UrzaUser construct(Map<String, String> fromData) {
        return getCONTEXT().getBean(UrzaUser.class, fromData);
    }

    public List<UrzaUser> findByRoleList(List<String> roles) {
        return getREPOSITORY().findByAuthoritiesIn(roles);

    }

    @EventListener(ApplicationReadyEvent.class)
    public boolean createAdminIfNone() {

        List<UrzaUser> tempList = getREPOSITORY().findByAuthoritiesIn(List.of("ROLE_ADMIN"));
        // List<UrzaUser> tempList = getREPOSITORY().findAll();
        if (tempList.size() == 0) {
            UrzaUser defaultAdmin = getCONTEXT().getBean(UrzaUser.class);

            defaultAdmin.setAuthorities(List.of("ROLE_ADMIN", "ROLE_USER"));
            defaultAdmin.setEmail("Mambo@cosmo.com");
            defaultAdmin.setUsername("UrzaAdmin");
            defaultAdmin.setDisplayName("UrzaAdmin");
            defaultAdmin.setPassword(getPasswordEncoder().encode("password"));
            defaultAdmin.setRegisterDate(Date.valueOf(LocalDate.now()));
            getURZAUSEREPOSITORY().save(defaultAdmin);
            System.out.println("Autogenerated default admin user because no admin were found.");
        }
        return true;

    }

    public boolean registerUser(Map<String, String> userData) {
        if (getURZAUSEREPOSITORY().findByUsername(userData.get("username")) != null) {
            return false;
        }
        if (getURZAUSEREPOSITORY().findByEmail(userData.get("email")) != null) {
            return false;
        }

        UrzaUser user = new UrzaUser();
        // user.setId(UUID.randomUUID());
        user.setUsername(userData.get("username"));
        user.setPassword(getPasswordEncoder().encode(userData.get("password")));
        user.setEmail(userData.get("email"));
        user.setDisplayName(userData.get("displayName")); // Default displayName = username
        user.setAuthorities(List.of("ROLE_USER"));
        user.setRegisterDate(Date.valueOf(LocalDate.now()));

        getURZAUSEREPOSITORY().save(user);
        return true;
    }

    public boolean registerAdmin(Map<String, String> userData) {
        if (getURZAUSEREPOSITORY().findByUsername(userData.get("username")) != null) {
            return false;
        }
        if (getURZAUSEREPOSITORY().findByEmail(userData.get("email")) != null) {
            return false;
        }

        UrzaUser user = new UrzaUser();
        // user.setId(UUID.randomUUID());
        user.setUsername(userData.get("username"));
        user.setPassword(getPasswordEncoder().encode(userData.get("password")));
        user.setEmail(userData.get("email"));
        user.setDisplayName(userData.get("displayName"));
        user.setAuthorities(List.of("ROLE_ADMIN"));
        user.setRegisterDate(Date.valueOf(LocalDate.now()));

        getURZAUSEREPOSITORY().save(user);
        return true;
    }

    public UrzaUser findByUsername(String username) {
        return getURZAUSEREPOSITORY().findByUsername(username);
    }

    public boolean updateUser(String username, Map<String, String> userData) {
        UrzaUser user = getURZAUSEREPOSITORY().findByUsername(username);
        if (user == null) {
            return false;
        }

        if (userData.containsKey("email")) {
            user.setEmail(userData.get("email"));
        }
        if (userData.containsKey("displayName")) {
            user.setDisplayName(userData.get("displayName"));
        }

        getURZAUSEREPOSITORY().save(user);
        return true;
    }

    public boolean changePassword(String username, String currentPassword, String newPassword) {
        UrzaUser user = getURZAUSEREPOSITORY().findByUsername(username);
        if (user == null) {
            return false;
        }

        if (!getPasswordEncoder().matches(currentPassword, user.getPassword())) {
            return false;
        }

        user.setPassword(getPasswordEncoder().encode(newPassword));
        getURZAUSEREPOSITORY().save(user);
        return true;
    }

    public boolean deleteUser(String username) {
        UrzaUser user = getURZAUSEREPOSITORY().findByUsername(username);
        if (user == null) {
            return false;
        }
        getURZAUSEREPOSITORY().delete(user);
        return true;
    }

    // METODI PER ADMIN
    public List<UrzaUser> findAllUsers() {
        return getURZAUSEREPOSITORY().findAll();
    }

    public void deleteUserById(UUID id) {
        getURZAUSEREPOSITORY().deleteById(id);
    }

    public UrzaUser findById(UUID id) {
        return getURZAUSEREPOSITORY().findById(id).orElse(null);
    }

    public boolean updateUserByAdmin(UUID userId, String username, String email, String displayName) {
        UrzaUser user = getURZAUSEREPOSITORY().findById(userId).orElse(null);
        if (user == null || user.isAdmin()) {
            return false;
        }

        // Verifica se username è già usato da un altro utente
        UrzaUser existingUser = getURZAUSEREPOSITORY().findByUsername(username);
        if (existingUser != null && !existingUser.getId().equals(userId)) {
            return false;
        }

        // Verifica se email è già usata da un altro utente
        UrzaUser existingEmail = getURZAUSEREPOSITORY().findByEmail(email);
        if (existingEmail != null && !existingEmail.getId().equals(userId)) {
            return false;
        }

        user.setUsername(username);
        user.setEmail(email);
        user.setDisplayName(displayName);
        getURZAUSEREPOSITORY().save(user);
        return true;
    }

    @Override
    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
        System.out.println("Loading user: " + username);
        return findByUsername(username);
    }

}
